import Head from 'next/head';
import { FC } from 'react';

const AppHead: FC<React.PropsWithChildren<unknown>> = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default AppHead;